; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; --- Base ESP32dev Environment ---
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; --- Base Arduino UNO Environment ---
[env:arduino_uno_base]
platform = atmelavr
board = uno
framework = arduino

; --- Fazla Env (ESP32) ---
[env:fazla_lift_esp]
extends = env:esp32dev
lib_deps =
  chris--a/Keypad@^3.1.1
  madhephaestus/ESP32Servo@^3.0.0
build_flags = -D PROJECT_FAZLA
src_filter =
  -<*>
  +<main.cpp>
  +<projectFazla/project-fazla.cpp>

; --- Fazla Env (Arduino UNO) ---
[env:fazla_lift_uno]
extends = env:arduino_uno_base
lib_deps =
  chris--a/Keypad@^3.1.1
  arduino-libraries/Servo @ ^1.2.2
build_flags = -D PROJECT_FAZLA
src_filter =
  -<*>
  +<main.cpp>
  +<projectFazla/project-fazla.cpp>

; --- Merlin Env (ESP32) ---
[env:merlin_smokedetector_esp]
extends = env:esp32dev
lib_deps =
  adafruit/DHT sensor library@^1.4.4
  adafruit/Adafruit Unified Sensor@^1.1.14
build_flags = -D PROJECT_MERLIN
src_filter =
  -<*>
  +<main.cpp>
  +<projectMerlin/project-merlin.cpp>
; --- Merlin Env (Arduino UNO) ---
[env:merlin_smokedetector_uno]
extends = env:arduino_uno_base
lib_deps =
  adafruit/DHT sensor library@^1.4.4
  adafruit/Adafruit Unified Sensor@^1.1.14
build_flags = -D PROJECT_MERLIN
src_filter =
  -<*>
  +<main.cpp>
  +<projectMerlin/project-merlin.cpp>
; --- Farrel Env (ESP32) ---
[env:farrel_hematListrik_esp]
extends = env:esp32dev
monitor_speed = 115200  ; Sesuai SERIAL_BAUD untuk ESP32
upload_speed = 921600   ; Default untuk ESP32, bisa disesuaikan
build_flags = -D PROJECT_FARREL
src_filter =
  -<*>
  +<main.cpp>


; --- Farrel Env (Arduino UNO) ---
[env:farrel_hematListrik_uno]
extends = env:arduino_uno_base
monitor_speed = 9600    ; Sesuai SERIAL_BAUD untuk Uno
upload_speed = 115200   ; Default untuk Uno, bisa disesuaikan
build_flags = -D PROJECT_FARREL
src_filter =
  -<*>
  +<main.cpp>


; --- Dipta Env (Arduino UNO) ---
[env:dipta_monitorParkir_uno]
extends = env:arduino_uno_base
lib_deps =
  Wire
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_flags = 
  -D PROJECT_DIPTA
  -D PROJECT_DIPTA_UNO
src_filter = -<*> +<main.cpp>

; --- Dipta Env (ESP32) ---
[env:dipta_monitorParkir_esp]
extends = env:esp32dev
lib_deps =
  Wire
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
build_flags = 
  -D PROJECT_DIPTA
  -D PROJECT_DIPTA_ESP
src_filter = -<*> +<main.cpp>

; --- Hilman Env (ESP32) ---
[env:hilman_smart-doorlock_esp]
extends = env:esp32dev
lib_deps = 
	miguelbalboa/MFRC522@^1.4.12
	bblanchon/ArduinoJson@^7.4.2
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.3
	plerup/EspSoftwareSerial@^8.1.0
build_flags = 
	-D PROJECT_HILMAN
src_filter = -<*> +<main.cpp> +<projectHilman/customer-door.cpp>


; --- Hilman Env (Arduino UNO) ---
[env:hilman_smart-doorlock_uno]
extends = env:arduino_uno_base
lib_deps = 
	miguelbalboa/MFRC522@^1.4.12
	bblanchon/ArduinoJson@^6.21.3  
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.3
	SoftwareSerial
build_flags = 
	-D PROJECT_HILMAN
src_filter = -<*> +<main.cpp> +<projectHilman/customer-door.cpp>

; --- Galih Env (ESP32) ---
[env:galih_smartCurtain_esp]
extends = env:esp32dev
lib_deps =
  BH1750
build_flags = 
  -D PROJECT_GALIH
  -D PROJECT_GALIH_ESP
src_filter = 
  -<*>                                              
  +<main.cpp>                                         
  +<modules/sensor_BH1750/module_sensor_BH1750.cpp>
  +<modules/pir/module_pir.cpp>                      
  +<modules/actuator_motor/module_motor.cpp>  

; --- Galih Env (Arduino UNO) ---
[env:galih_smartCurtain_uno]
extends = env:arduino_uno_base
lib_deps =
  BH1750
build_flags = 
  -D PROJECT_GALIH
  -D PROJECT_GALIH_UNO
src_filter = 
  -<*>                                              
  +<main.cpp>                                         
  +<modules/sensor_BH1750/module_sensor_BH1750.cpp>
  +<modules/pir/module_pir.cpp>                      
  +<modules/actuator_motor/module_motor.cpp> 